/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package apresentacao_rent;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import rent.car.negocio.Carro;
import rent.car.negocio.Reserva;
import rent.car.presitenciadados.ControlaCarro;
import rent.car.presitenciadados.Controldareserva;

/**
 *
 * @author PC
 */
public class Alugar_viatura extends javax.swing.JFrame {

    /**
     * Creates new form Alugar_viatura
     */
  
    ControlaCarro cr;
    Controldareserva cc ; 
     
   private ArrayList <Carro> carros_r=new ArrayList<>();
   private ArrayList <Reserva> carros_rv=new ArrayList<>();
   

    public Alugar_viatura(ControlaCarro cc,Controldareserva crr) {
        initComponents();
        this.carros_r = cc.retonaTodos();
        this.carros_rv = crr.retonaTodos();
        this.cc=crr;
        
    }

    private Alugar_viatura() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome_carro = new javax.swing.JTextField();
        matricula_carro = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btn_cancelar_alugar_viatura = new javax.swing.JButton();
        btn_gravar_alugar_viatura = new javax.swing.JButton();
        tempo_carro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Nome da Viatura");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Matricula da Viatura");

        nome_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nome_carroActionPerformed(evt);
            }
        });

        matricula_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matricula_carroActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Alugar Viatura");

        btn_cancelar_alugar_viatura.setText("Cancelar");
        btn_cancelar_alugar_viatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelar_alugar_viaturaActionPerformed(evt);
            }
        });

        btn_gravar_alugar_viatura.setText("Alugar");
        btn_gravar_alugar_viatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gravar_alugar_viaturaActionPerformed(evt);
            }
        });

        tempo_carro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tempo_carroActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Tempo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(btn_gravar_alugar_viatura, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_cancelar_alugar_viatura, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nome_carro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 289, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 131, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(matricula_carro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tempo_carro)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nome_carro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(matricula_carro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tempo_carro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cancelar_alugar_viatura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_gravar_alugar_viatura, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nome_carroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nome_carroActionPerformed

    private void matricula_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matricula_carroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matricula_carroActionPerformed

    private void btn_gravar_alugar_viaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gravar_alugar_viaturaActionPerformed
         // TODO add your handling code here:

        Reserva carro = new Reserva();
        
        carro.setNome_carro(nome_carro.getText());
        carro.setMatricula_carro(matricula_carro.getText());
        carro.setTempo_carro(tempo_carro.getText());
 
        boolean tem_daddos=true;
        boolean tem_daddos_reserva=false;
        ////////////////////////////////////////////////////////////////////////
            for(int i = 0; i < carros_r.size(); i ++){
            if(carros_r.get(i).getNomeOrganizacao().equals(nome_carro.getText())&&carros_r.get(i).getMatricula().equals(matricula_carro.getText())){  
                tem_daddos=false;
            }   
        }
               for(int i = 0; i < carros_rv.size(); i ++){
            if(carros_rv.get(i).getNome_carro().equals(nome_carro.getText())&&carros_rv.get(i).getMatricula_carro().equals(matricula_carro.getText())){  
                tem_daddos_reserva=true;
                break;
            }   
        }
               if(tem_daddos_reserva){
                JOptionPane.showMessageDialog(null, "Este carro já foi Alugado !");
                 return;
            }
            
            if(tem_daddos){
                JOptionPane.showMessageDialog(null, "Ups Dados não encotrado !");
                 return;
            }
        ///////////////////////////////////////////////////////////////

        if (cc.alugar_carro(carro)) {
            JOptionPane.showMessageDialog(null, "Carro Reservado com sucesso!");
            nome_carro.setText("");
            matricula_carro.setText("");
            tempo_carro.setText("");
        } else {
            JOptionPane.showMessageDialog(null, "Ups Erro ao cadastrar o seu carro !S");
        }
    }//GEN-LAST:event_btn_gravar_alugar_viaturaActionPerformed

    private void btn_cancelar_alugar_viaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelar_alugar_viaturaActionPerformed
        // TODO add your handling code here:
      this.dispose();
      
    }//GEN-LAST:event_btn_cancelar_alugar_viaturaActionPerformed

    private void tempo_carroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tempo_carroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tempo_carroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alugar_viatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alugar_viatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alugar_viatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alugar_viatura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alugar_viatura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancelar_alugar_viatura;
    private javax.swing.JButton btn_gravar_alugar_viatura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField matricula_carro;
    private javax.swing.JTextField nome_carro;
    private javax.swing.JTextField tempo_carro;
    // End of variables declaration//GEN-END:variables
}
